# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145d5ad85b4a4ca921ee74938abe8eaeec2843ef705bf8b1eb8c8acab241914b851d28f3c508018fc9bcb2e04e370ec7390894b0a0c38b3b64da548f965a6573

test:
  secret_key_base: af1b76180ea0cab28ad129d3b513d2c0c866c8036424d1dbe1d4f5c86817572c87993c965fe11c62cac9ed901bf54a2f8c38a50c297703325df48f7d4a8a52ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
